### ISSUE TITLE
write explicit goals for end result of UI

### ISSUE THREAD

**Issue by natebrennand** [natebrennand/cpp_collections#1]
- no template overhead to calling functions
  - we will do this with template magic that 
  - i.e. `c.map(add)` (not `c.map<int>(add()`)
- minimal performance overhead
  - should be within 5% of [`accumulate`](http://www.cplusplus.com/reference/numeric/accumulate/) or equivalent operations
- catch all errors at compile time
  - this means extensive static assertions on the function objects passed in

**Comment by ianzapolsky** [comment]
agreed

**Comment by natebrennand** [comment]
I updated the initial comment with what we seemed to come to in our first meeting.
