### ISSUE TITLE
implementation style

### ISSUE THREAD

**Issue by natebrennand** [natebrennand/cpp_collections#11]
I think it might be more manageable if we only define the function prototype within the main class declaration in `collections.h` and fully define the functions in the body below.

Thoughts?

**Comment by ianzapolsky** [comment]
yea sounds good

**Comment by ianzapolsky** [comment]
when you say "body below" what exactly do you mean?

**Comment by natebrennand** [comment]
placing methods like this:

```cpp
template<typename T>
class Collection {
private:
    std::vector<T> Data;
public:
    Collection<T>(std::vector<T> d){
        Data = d;
    };

    void
    print();

};

template<typename T>
void
Collection<T>::print() {
    std::cout << "[";
    for (int i = 0; i < Data.size() - 1; i++)
        std::cout << Data[i] << ",";
    std::cout << Data[Data.size() - 1] << "]" << std::endl;
};
```

I think it's already getting a bit difficult to navigate the file and it will only get more cluttered as we add more methods.

**Comment by ianzapolsky** [comment]
great i see
