### ISSUE TITLE
implement basic list combination methods

### ISSUE THREAD

**Issue by ianzapolsky** [natebrennand/cpp_collections#14]
- [x] zip
- [x] zipWith

**Comment by natebrennand** [comment]
Should we have `zip` yield a list of [`pair`s](http://www.cplusplus.com/reference/utility/pair/)?

**Comment by ianzapolsky** [comment]
see the comment on the PR just now. We should discuss whether we want zip to return a list of pairs our tuples.

**Comment by ianzapolsky** [comment]
obviously, if we see ourselves wanting to implement [zip3](https://www.haskell.org/hoogle/?hoogle=zip3) in the future, tuples might make more sense

**Comment by natebrennand** [comment]
If we can get `tuple` to work with variadic templates I feel like it would be best to use tuples for all `zip` operations
