### ISSUE TITLE
create namespace as alternative to static class functions

### ISSUE THREAD

**Issue by ianzapolsky** [natebrennand/cpp_collections#19]
see most recent comments on combinations PR

**Comment by ianzapolsky** [comment]
see most recent comments on combinations PR

**Comment by natebrennand** [comment]
I'm fine with doing it this way. I don't really have any experience with non-STL libraries to know what the usual procedure is.

**Comment by ianzapolsky** [comment]
in addition to range functions, and zip/zipWith functions, we can also define a base set of lambdas that we'd like to include in our library, like `add`, etc.
