### ISSUE TITLE
write syntax benchmarks

### ISSUE THREAD

**Issue by ianzapolsky** [natebrennand/cpp_collections#20]
short programs that show off the syntactical efficiency of our library when compared with standard C++.

**Comment by natebrennand** [comment]
isn't this a dupe of #4?

**Comment by ianzapolsky** [comment]
This issue differs from #4 because it is strictly focused on syntax. The performance of these programs should irrelevant; they are more like syntactical showcases. 

It may turn out that our performance benchmarking programs serve this purpose just fine, in which case these won't be necessary

**Comment by ianzapolsky** [comment]
This issue differs from #4 because it is strictly focused on syntax. The performance of these programs should irrelevant; they are more like syntactical showcases. 

It may turn out that our performance benchmarking programs serve this purpose just fine, in which case these won't be necessary

**Comment by udaysinghcode** [comment]
This I'm assuming is for documentation? I can work on some of these and begin setting up the documentation as we need both a design document and a tutorial document of around 15 pages each. I may just start writing it out.

**Comment by natebrennand** [comment]
Do you want to do it in latex or google docs?
I advocate for latex because then it keeps the entire source of the project in 1 location/repo and we can ensure that it's properly updated as changes to the library are made.

**Comment by udaysinghcode** [comment]
I'm down for either - I've never used Latex but it would be a good time to learn.
