### ISSUE TITLE
Start Latex Documentation

### ISSUE THREAD

**Issue by udaysinghcode** [natebrennand/cpp_collections#21]
I'm just installing Latex now - I have a problem set tonight, but I'll push something today or tomorrow to get the whole thing started. This was as @natebrennand said in #20 - so we can keep it all together in one repo.

**Comment by natebrennand** [comment]
@udaysinghcode, has there been progress on this?
It'd be great if you had a PR open as you went so that we can review

**Comment by udaysinghcode** [comment]
Hey man - yeah it's a bit of a mess (I have work all day today) - let me clean more of it up, I'll push it and work from there so we can keep updating it together. My bad
