### ISSUE TITLE
try simplifying range

### ISSUE THREAD

**Issue by natebrennand** [natebrennand/cpp_collections#33]
Ideal:
```cpp
Collection<int32> l = range(20);
```

current:
```cpp
auto l = range(int32(20));
```

-----

POI: http://stackoverflow.com/questions/25375118/template-parameter-based-on-expected-return-type

**Comment by ianzapolsky** [comment]
One potential issue with this approach would be when we don't declare the collection at all, i.e.

```
    sum = range(1,101)
              .map([](int x) {return x * x;})
              .reduceLeft([](int x, int y) {return x + y;});
```

**Comment by natebrennand** [comment]
eek, i guess this is a bust.
