### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by natebrennand** [natebrennand/cpp_collections#46]
Tutorial
- 10-15 pages
- See “How to write a tutorial”

**Comment by natebrennand** [comment]
# Slides

![how-to-write-a-tutorial 001](https://cloud.githubusercontent.com/assets/2801090/7381452/7a24affc-edd1-11e4-8d20-62a4407ec004.png)
![how-to-write-a-tutorial 002](https://cloud.githubusercontent.com/assets/2801090/7381454/7a250448-edd1-11e4-9fe6-652be361f1cc.png)
![how-to-write-a-tutorial 003](https://cloud.githubusercontent.com/assets/2801090/7381457/7a25d300-edd1-11e4-8600-9485c626b8b8.png)
![how-to-write-a-tutorial 004](https://cloud.githubusercontent.com/assets/2801090/7381455/7a257608-edd1-11e4-8089-543561f6bc2d.png)
![how-to-write-a-tutorial 005](https://cloud.githubusercontent.com/assets/2801090/7381453/7a24afa2-edd1-11e4-9ab3-8c95eaaaaf4a.png)
![how-to-write-a-tutorial 006](https://cloud.githubusercontent.com/assets/2801090/7381456/7a259142-edd1-11e4-8ed3-e703fbe40743.png)

**Comment by udaysinghcode** [comment]
Yeah I'm working on this right now
