### ISSUE TITLE
setup continuous integration

### ISSUE THREAD

**Issue by natebrennand** [natebrennand/cpp_collections#5]
Ensure that our library will always compile.
Possibly also run benchmarks.

I'm familiar with Travis-CI and will use that unless someone else has a strong preference.

**Comment by ianzapolsky** [comment]
i'm totally unfamiliar with setting up continuous integration and would love to double on it to see how it's done.

**Comment by natebrennand** [comment]
Sounds good, it's pretty straightforward when you're using a free service like Travis which handles all the hard parts.

**Comment by natebrennand** [comment]
So with the test scrips implemented this will be super easy. We can add it the next time we meet.

**Comment by udaysinghcode** [comment]
Yeah I'm unfamiliar as well - seconded Ian - would like to meet up to do that. I see it used on open source stuff all the time.

**Comment by natebrennand** [comment]
Let's plan to do that Friday afternoon after class.
