### ISSUE TITLE
range implementation

### ISSUE THREAD

**Issue by natebrennand** [natebrennand/cpp_collections#9]
So I think we might have had different ideas of what the `range()` fn should do.

My impressions was that it generates a Collection of integers(or another numeric type) from `a` to `b`. [example](https://docs.python.org/2/library/functions.html#range)

Currently it's a mix between filter and a slice operator.

-------

- I think we should use the `range` function to generate a list of integers/doubles.
- I think we should write a `slice` (or another name) function that returns elements from a collection between index `a` and `b`.

thoughts?

**Comment by ianzapolsky** [comment]
agreed. so then, would range create a new vector and completely overwrite the existing Data?

**Comment by natebrennand** [comment]
I thought that range should be a static method that returns a new collection.

**Comment by ianzapolsky** [comment]
in other words, not a member function of Collection class?

**Comment by natebrennand** [comment]
It doesn't strictly need to be a member. But we can implement it with a `static method`
